### ISSUE TITLE
The 'core' and 'utils' package names

### ISSUE THREAD

**Issue by noootwo** [initx-collective/initx#6]
Why are the 'core' and 'utils' package names prefixed with '@initx-plugin/'? I think they are core packages, so maybe it would be better to prefix them with '@initx/'.

**Comment by imba97** [comment]
最开始试过，但 `initx` 这个名不能创建组织，应该是有个人叫 `initx`，默认是他的组织

`@initx-plugin/core`、`@initx-plugin/utils` 也是合理的，因为都是跟插件相关的，插件会用到的

**Comment by noootwo** [comment]
了解，不过这样是挺容易有些误解的，我建议在早期可以琢磨处理下

**Comment by imba97** [comment]
@noootwo 

好嘞，感谢提醒，确实需要早期做决定

目前名字这块我感觉还行，比如开发插件的时候

```ts
import { type InitxCtx, InitxHandler } from '@initx-plugin/core'
import { log } from '@initx-plugin/utils'

export default class MyHandler extends InitxHandler {
}
```

这样还算比较合理，倒是 `InitxHandler` 这个类名我考虑换成 `InitxPlugin`

即使不叫 `@initx-plugin`，那也得想一个 `@initx-xxx`，感觉别的也没啥像 `@initx-plugin` 意思明确的

**Comment by noootwo** [comment]
或许可以换个方向想想，我理解最初叫”initx“是因为是想做初始化脚本的快捷方式？现在这个库更像是对于任何操作的快捷方式，不再仅仅是”init“，或许可以重新构思个名字？（虽然这是一件很麻烦的事）

**Comment by imba97** [comment]
最开始确实是为了更方便的初始化，确实后面调整不仅限于初始化，而是脚本简化之类的工作

开始也纠结过名字的问题，但后来想了想其实也还好，它只是个名字

再加上刚好 `initx` 报名和 `initx-plugin` 组织名都可以用，目前没有改名的打算了

**Comment by noootwo** [comment]
这样也挺好

**Comment by imba97** [comment]
感谢提供想法
